---
- name: Log in (obtain access token)
  redhat.openshift.openshift_auth:
    username: "{{ openshift_upgrade_checks_username | mandatory }}"
    password: "{{ openshift_upgrade_checks_password | mandatory }}"
  register: openshift_auth_results
